---
title: "Date Formatting"
output: html_document
---

One of  my biggest bug bears are dates. As dull as it sounds, formatting dates correctly is a fundamental part of data cleaning in healthcare. This is especially true if your data objects are event-driven (which is to say you collect events that happen at time-points such as the time a patient enters an endoscopy room or the day the endoscopy was done etc.). In addition, the correct and standardised formatting of dates will allow you to merge data from separate data sources and still understand a unified sequence of events. Eventing, as I call it, is fundamental to understanding processes and its inefficiences.

Given it is so important, perhaps the correct formatting of dates is not so boring after all.

#Date formats:
Dates come in may forms, but in R the main formats are as follows:

#####1.POSIXct or POSIXlt - stores dates and times and can manipulate timezones

#####2.Date - date without times

#####3.Character

#####4.Numeric (the usual way it is stored when imported from Excel and refers to the number of days or seconds from an origin date)

#####5.On top of the above, dates even within the same format can be of different combinations such as the day or the month being first, or an abbreviated year etc.
Most of the time when importing, the dates will be in character format.but not always.

##How to convert to date format:
The finest level of granularity I usually require is day. This means that the as.Date function, part of base R, is usually sufficient Occasionally I need hours which requires a slightly different approach. Below are some examples:

Conversion from text  and numeric to Date or POSIXct
1.Conversion from numeric to Date
2.Conversion from text to POSIXct
3.Conversion from numeric to POSIXct
Using libraries for dates
1.lubridate
2.anytime
3.chron
